totalShards=6 # Seperating index / data by 'totalShards'
replicas=1 # having 'replicas' copies of each shard. Primary and replicas should never be on same node
node-a=localhost:9091
node-b=localhost:9092
node-c=localhost:9093
